package com.ljstudio.android.loveday.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ljstudio.android.loveday.entity.DaysData;
import com.ljstudio.android.loveday.entity.TestData;

import com.ljstudio.android.loveday.greendao.DaysDataDao;
import com.ljstudio.android.loveday.greendao.TestDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daysDataDaoConfig;
    private final DaoConfig testDataDaoConfig;

    private final DaysDataDao daysDataDao;
    private final TestDataDao testDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daysDataDaoConfig = daoConfigMap.get(DaysDataDao.class).clone();
        daysDataDaoConfig.initIdentityScope(type);

        testDataDaoConfig = daoConfigMap.get(TestDataDao.class).clone();
        testDataDaoConfig.initIdentityScope(type);

        daysDataDao = new DaysDataDao(daysDataDaoConfig, this);
        testDataDao = new TestDataDao(testDataDaoConfig, this);

        registerDao(DaysData.class, daysDataDao);
        registerDao(TestData.class, testDataDao);
    }
    
    public void clear() {
        daysDataDaoConfig.clearIdentityScope();
        testDataDaoConfig.clearIdentityScope();
    }

    public DaysDataDao getDaysDataDao() {
        return daysDataDao;
    }

    public TestDataDao getTestDataDao() {
        return testDataDao;
    }

}
