package cn.ljstudio.android.loveday.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ljstudio.android.loveday.entity.DaysData;

import cn.ljstudio.android.loveday.greendao.DaysDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daysDataDaoConfig;

    private final DaysDataDao daysDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daysDataDaoConfig = daoConfigMap.get(DaysDataDao.class).clone();
        daysDataDaoConfig.initIdentityScope(type);

        daysDataDao = new DaysDataDao(daysDataDaoConfig, this);

        registerDao(DaysData.class, daysDataDao);
    }
    
    public void clear() {
        daysDataDaoConfig.clearIdentityScope();
    }

    public DaysDataDao getDaysDataDao() {
        return daysDataDao;
    }

}
